// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/meshsecurity/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryVirtualStakingMaxCapRequest is the request type for the
// Query/VirtualStakingMaxCap RPC method
type QueryVirtualStakingMaxCapRequest struct {
	// address is the address of the contract to query
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryVirtualStakingMaxCapRequest) Reset()         { *m = QueryVirtualStakingMaxCapRequest{} }
func (m *QueryVirtualStakingMaxCapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVirtualStakingMaxCapRequest) ProtoMessage()    {}
func (*QueryVirtualStakingMaxCapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c89ba006eed4fb, []int{0}
}

func (m *QueryVirtualStakingMaxCapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryVirtualStakingMaxCapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVirtualStakingMaxCapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryVirtualStakingMaxCapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVirtualStakingMaxCapRequest.Merge(m, src)
}

func (m *QueryVirtualStakingMaxCapRequest) XXX_Size() int {
	return m.Size()
}

func (m *QueryVirtualStakingMaxCapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVirtualStakingMaxCapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVirtualStakingMaxCapRequest proto.InternalMessageInfo

// QueryVirtualStakingMaxCapResponse is the response type for the
// Query/VirtualStakingMaxCap RPC method
type QueryVirtualStakingMaxCapResponse struct {
	Limit *types.Coin `protobuf:"bytes,6,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *QueryVirtualStakingMaxCapResponse) Reset()         { *m = QueryVirtualStakingMaxCapResponse{} }
func (m *QueryVirtualStakingMaxCapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVirtualStakingMaxCapResponse) ProtoMessage()    {}
func (*QueryVirtualStakingMaxCapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c89ba006eed4fb, []int{1}
}

func (m *QueryVirtualStakingMaxCapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryVirtualStakingMaxCapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVirtualStakingMaxCapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryVirtualStakingMaxCapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVirtualStakingMaxCapResponse.Merge(m, src)
}

func (m *QueryVirtualStakingMaxCapResponse) XXX_Size() int {
	return m.Size()
}

func (m *QueryVirtualStakingMaxCapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVirtualStakingMaxCapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVirtualStakingMaxCapResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryVirtualStakingMaxCapRequest)(nil), "osmosis.meshsecurity.v1beta1.QueryVirtualStakingMaxCapRequest")
	proto.RegisterType((*QueryVirtualStakingMaxCapResponse)(nil), "osmosis.meshsecurity.v1beta1.QueryVirtualStakingMaxCapResponse")
}

func init() {
	proto.RegisterFile("osmosis/meshsecurity/v1beta1/query.proto", fileDescriptor_50c89ba006eed4fb)
}

var fileDescriptor_50c89ba006eed4fb = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xbf, 0x4a, 0x03, 0x41,
	0x10, 0xc6, 0x6f, 0xc5, 0x44, 0x3c, 0xbb, 0x23, 0x45, 0x0c, 0x61, 0x8d, 0xa9, 0xd2, 0x64, 0x97,
	0xc4, 0x42, 0x10, 0x89, 0x60, 0x6a, 0x0b, 0x23, 0x58, 0xa4, 0xd1, 0xbd, 0xcb, 0x72, 0x59, 0x72,
	0xb7, 0x7b, 0xb9, 0xd9, 0x93, 0x04, 0xb1, 0xf1, 0x09, 0x04, 0x5f, 0xc0, 0xd2, 0x47, 0x49, 0x19,
	0xb0, 0x11, 0x2b, 0xbd, 0x58, 0xf8, 0x18, 0x92, 0xfb, 0x23, 0x0a, 0x12, 0xc1, 0x6e, 0xee, 0xe6,
	0xfb, 0xe6, 0xdb, 0xdf, 0x8c, 0xd9, 0x50, 0xe0, 0x2b, 0x10, 0x40, 0x7d, 0x0e, 0x43, 0xe0, 0x4e,
	0x14, 0x0a, 0x3d, 0xa5, 0x57, 0x2d, 0x9b, 0x6b, 0xd6, 0xa2, 0xe3, 0x88, 0x87, 0x53, 0x12, 0x84,
	0x4a, 0x2b, 0xab, 0x9a, 0x29, 0xc9, 0x77, 0x25, 0xc9, 0x94, 0x15, 0xec, 0x24, 0x6d, 0x6a, 0x33,
	0xe0, 0x5f, 0x76, 0x47, 0x09, 0x99, 0xba, 0x2b, 0x25, 0x57, 0xb9, 0x2a, 0x29, 0xe9, 0xb2, 0xca,
	0xfe, 0x56, 0x5d, 0xa5, 0x5c, 0x8f, 0x53, 0x16, 0x08, 0xca, 0xa4, 0x54, 0x9a, 0x69, 0xa1, 0x24,
	0xa4, 0xdd, 0xfa, 0xa1, 0x59, 0x3b, 0x5d, 0x3e, 0xe0, 0x5c, 0x84, 0x3a, 0x62, 0xde, 0x99, 0x66,
	0x23, 0x21, 0xdd, 0x13, 0x36, 0xe9, 0xb2, 0xa0, 0xc7, 0xc7, 0x11, 0x07, 0x6d, 0x95, 0xcd, 0x0d,
	0x36, 0x18, 0x84, 0x1c, 0xa0, 0x8c, 0x6a, 0xa8, 0xb1, 0xd9, 0xcb, 0x3f, 0xeb, 0x7d, 0x73, 0x77,
	0x85, 0x1b, 0x02, 0x25, 0x81, 0x5b, 0xd4, 0x2c, 0x78, 0xc2, 0x17, 0xba, 0x5c, 0xac, 0xa1, 0xc6,
	0x56, 0x7b, 0x9b, 0xa4, 0x18, 0x64, 0x89, 0x91, 0xb3, 0x91, 0xae, 0x12, 0xb2, 0x97, 0xea, 0x0e,
	0xd6, 0x3f, 0x1e, 0x76, 0x50, 0xfb, 0x05, 0x99, 0x85, 0x64, 0xb8, 0x35, 0x47, 0x66, 0xe9, 0xb7,
	0x04, 0xab, 0x43, 0x56, 0xed, 0x8b, 0xfc, 0x05, 0x56, 0x39, 0xfa, 0xb7, 0x3f, 0x45, 0xab, 0xef,
	0xdf, 0x3e, 0xbd, 0xdf, 0xaf, 0xb5, 0x2c, 0x4a, 0x57, 0x9e, 0xd8, 0x67, 0x93, 0x0b, 0x87, 0x05,
	0xf4, 0x3a, 0xdb, 0xdb, 0xcd, 0xf1, 0xe5, 0xec, 0x0d, 0x1b, 0x8f, 0x31, 0x36, 0x66, 0x31, 0x46,
	0xf3, 0x18, 0xa3, 0xd7, 0x18, 0xa3, 0xbb, 0x05, 0x36, 0xe6, 0x0b, 0x6c, 0x3c, 0x2f, 0xb0, 0xd1,
	0xef, 0xb8, 0x42, 0x0f, 0x23, 0x9b, 0x38, 0xca, 0xcf, 0x87, 0x37, 0x3d, 0x66, 0xa7, 0x09, 0xcd,
	0x3c, 0xa2, 0x09, 0x83, 0x11, 0x9d, 0xfc, 0x4c, 0xd5, 0xd3, 0x80, 0x83, 0x5d, 0x4c, 0xee, 0xbb,
	0xf7, 0x19, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x5e, 0x91, 0xec, 0x7d, 0x02, 0x00, 0x00,
}

func (this *QueryVirtualStakingMaxCapResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryVirtualStakingMaxCapResponse)
	if !ok {
		that2, ok := that.(QueryVirtualStakingMaxCapResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Limit.Equal(that1.Limit) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConn
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ContractInfo gets the contract meta data
	VirtualStakingMaxCap(ctx context.Context, in *QueryVirtualStakingMaxCapRequest, opts ...grpc.CallOption) (*QueryVirtualStakingMaxCapResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) VirtualStakingMaxCap(ctx context.Context, in *QueryVirtualStakingMaxCapRequest, opts ...grpc.CallOption) (*QueryVirtualStakingMaxCapResponse, error) {
	out := new(QueryVirtualStakingMaxCapResponse)
	err := c.cc.Invoke(ctx, "/osmosis.meshsecurity.v1beta1.Query/VirtualStakingMaxCap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ContractInfo gets the contract meta data
	VirtualStakingMaxCap(context.Context, *QueryVirtualStakingMaxCapRequest) (*QueryVirtualStakingMaxCapResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct{}

func (*UnimplementedQueryServer) VirtualStakingMaxCap(ctx context.Context, req *QueryVirtualStakingMaxCapRequest) (*QueryVirtualStakingMaxCapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VirtualStakingMaxCap not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_VirtualStakingMaxCap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVirtualStakingMaxCapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VirtualStakingMaxCap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.meshsecurity.v1beta1.Query/VirtualStakingMaxCap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VirtualStakingMaxCap(ctx, req.(*QueryVirtualStakingMaxCapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.meshsecurity.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VirtualStakingMaxCap",
			Handler:    _Query_VirtualStakingMaxCap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/meshsecurity/v1beta1/query.proto",
}

func (m *QueryVirtualStakingMaxCapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVirtualStakingMaxCapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVirtualStakingMaxCapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVirtualStakingMaxCapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVirtualStakingMaxCapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVirtualStakingMaxCapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Limit != nil {
		{
			size, err := m.Limit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *QueryVirtualStakingMaxCapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVirtualStakingMaxCapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Limit != nil {
		l = m.Limit.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *QueryVirtualStakingMaxCapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVirtualStakingMaxCapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVirtualStakingMaxCapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryVirtualStakingMaxCapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVirtualStakingMaxCapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVirtualStakingMaxCapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Limit == nil {
				m.Limit = &types.Coin{}
			}
			if err := m.Limit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
