// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/types/v1beta1/wire.proto

package types

import (
	fmt "fmt"
	_ "github.com/cometbft/cometbft/abci/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// enum PipedValsetOperation
type PipedValsetOperation int32

const (
	PipedValsetOperation_UNSPECIFIED          PipedValsetOperation = 0
	PipedValsetOperation_VALIDATOR_BONDED     PipedValsetOperation = 1
	PipedValsetOperation_VALIDATOR_UNBONDED   PipedValsetOperation = 2
	PipedValsetOperation_VALIDATOR_JAILED     PipedValsetOperation = 3
	PipedValsetOperation_VALIDATOR_TOMBSTONED PipedValsetOperation = 4
	PipedValsetOperation_VALIDATOR_UNJAILED   PipedValsetOperation = 5
	PipedValsetOperation_VALIDATOR_MODIFIED   PipedValsetOperation = 6
	PipedValsetOperation_VALIDATOR_SLASHED    PipedValsetOperation = 7
)

var PipedValsetOperation_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "VALIDATOR_BONDED",
	2: "VALIDATOR_UNBONDED",
	3: "VALIDATOR_JAILED",
	4: "VALIDATOR_TOMBSTONED",
	5: "VALIDATOR_UNJAILED",
	6: "VALIDATOR_MODIFIED",
	7: "VALIDATOR_SLASHED",
}

var PipedValsetOperation_value = map[string]int32{
	"UNSPECIFIED":          0,
	"VALIDATOR_BONDED":     1,
	"VALIDATOR_UNBONDED":   2,
	"VALIDATOR_JAILED":     3,
	"VALIDATOR_TOMBSTONED": 4,
	"VALIDATOR_UNJAILED":   5,
	"VALIDATOR_MODIFIED":   6,
	"VALIDATOR_SLASHED":    7,
}

func (x PipedValsetOperation) String() string {
	return proto.EnumName(PipedValsetOperation_name, int32(x))
}

func (PipedValsetOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c573c9158aa3b788, []int{0}
}

// InfractionType indicates the infraction type a validator committed.
// Note ccv.InfractionType to maintain compatibility between ICS versions
// using different versions of the cosmos-sdk and ibc-go modules.
type InfractionType int32

const (
	// UNSPECIFIED defines an empty infraction type.
	InfractionEmpty InfractionType = 0
	// DOUBLE_SIGN defines a validator that double-signs a block.
	DoubleSign InfractionType = 1
	// DOWNTIME defines a validator that missed signing too many blocks.
	Downtime InfractionType = 2
)

var InfractionType_name = map[int32]string{
	0: "INFRACTION_TYPE_UNSPECIFIED",
	1: "INFRACTION_TYPE_DOUBLE_SIGN",
	2: "INFRACTION_TYPE_DOWNTIME",
}

var InfractionType_value = map[string]int32{
	"INFRACTION_TYPE_UNSPECIFIED": 0,
	"INFRACTION_TYPE_DOUBLE_SIGN": 1,
	"INFRACTION_TYPE_DOWNTIME":    2,
}

func (x InfractionType) String() string {
	return proto.EnumName(InfractionType_name, int32(x))
}

func (InfractionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c573c9158aa3b788, []int{1}
}

// SlashInfo defines info event from slashing
type SlashInfo struct {
	Validator        string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	InfractionHeight int64  `protobuf:"varint,2,opt,name=infraction_height,json=infractionHeight,proto3" json:"infraction_height,omitempty"`
	Power            int64  `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	TotalSlashAmount string `protobuf:"bytes,4,opt,name=total_slash_amount,json=totalSlashAmount,proto3" json:"total_slash_amount,omitempty"`
	SlashFraction    string `protobuf:"bytes,5,opt,name=slash_fraction,json=slashFraction,proto3" json:"slash_fraction,omitempty"`
	TimeInfraction   int64  `protobuf:"varint,6,opt,name=time_infraction,json=timeInfraction,proto3" json:"time_infraction,omitempty"`
}

func (m *SlashInfo) Reset()         { *m = SlashInfo{} }
func (m *SlashInfo) String() string { return proto.CompactTextString(m) }
func (*SlashInfo) ProtoMessage()    {}
func (*SlashInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c573c9158aa3b788, []int{0}
}
func (m *SlashInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SlashInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SlashInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SlashInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashInfo.Merge(m, src)
}
func (m *SlashInfo) XXX_Size() int {
	return m.Size()
}
func (m *SlashInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SlashInfo proto.InternalMessageInfo

// InfoSchedule
type ScheduleInfo struct {
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Actor     string `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (m *ScheduleInfo) Reset()         { *m = ScheduleInfo{} }
func (m *ScheduleInfo) String() string { return proto.CompactTextString(m) }
func (*ScheduleInfo) ProtoMessage()    {}
func (*ScheduleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c573c9158aa3b788, []int{1}
}
func (m *ScheduleInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduleInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleInfo.Merge(m, src)
}
func (m *ScheduleInfo) XXX_Size() int {
	return m.Size()
}
func (m *ScheduleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleInfo proto.InternalMessageInfo

// ConsumerPacketData contains a consumer packet data and a type tag
type ConsumerPacketData struct {
	Type PipedValsetOperation `protobuf:"varint,1,opt,name=type,proto3,enum=osmosis.types.v1beta1.PipedValsetOperation" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ConsumerPacketData_SlashPacketData
	//	*ConsumerPacketData_SchedulePacketData
	Data isConsumerPacketData_Data `protobuf_oneof:"data"`
}

func (m *ConsumerPacketData) Reset()         { *m = ConsumerPacketData{} }
func (m *ConsumerPacketData) String() string { return proto.CompactTextString(m) }
func (*ConsumerPacketData) ProtoMessage()    {}
func (*ConsumerPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c573c9158aa3b788, []int{2}
}
func (m *ConsumerPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerPacketData.Merge(m, src)
}
func (m *ConsumerPacketData) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerPacketData proto.InternalMessageInfo

type isConsumerPacketData_Data interface {
	isConsumerPacketData_Data()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ConsumerPacketData_SlashPacketData struct {
	SlashPacketData *SlashInfo `protobuf:"bytes,2,opt,name=slashPacketData,proto3,oneof" json:"slashPacketData,omitempty"`
}
type ConsumerPacketData_SchedulePacketData struct {
	SchedulePacketData *ScheduleInfo `protobuf:"bytes,3,opt,name=schedulePacketData,proto3,oneof" json:"schedulePacketData,omitempty"`
}

func (*ConsumerPacketData_SlashPacketData) isConsumerPacketData_Data()    {}
func (*ConsumerPacketData_SchedulePacketData) isConsumerPacketData_Data() {}

func (m *ConsumerPacketData) GetData() isConsumerPacketData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ConsumerPacketData) GetSlashPacketData() *SlashInfo {
	if x, ok := m.GetData().(*ConsumerPacketData_SlashPacketData); ok {
		return x.SlashPacketData
	}
	return nil
}

func (m *ConsumerPacketData) GetSchedulePacketData() *ScheduleInfo {
	if x, ok := m.GetData().(*ConsumerPacketData_SchedulePacketData); ok {
		return x.SchedulePacketData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConsumerPacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConsumerPacketData_SlashPacketData)(nil),
		(*ConsumerPacketData_SchedulePacketData)(nil),
	}
}

func init() {
	proto.RegisterEnum("osmosis.types.v1beta1.PipedValsetOperation", PipedValsetOperation_name, PipedValsetOperation_value)
	proto.RegisterEnum("osmosis.types.v1beta1.InfractionType", InfractionType_name, InfractionType_value)
	proto.RegisterType((*SlashInfo)(nil), "osmosis.types.v1beta1.SlashInfo")
	proto.RegisterType((*ScheduleInfo)(nil), "osmosis.types.v1beta1.ScheduleInfo")
	proto.RegisterType((*ConsumerPacketData)(nil), "osmosis.types.v1beta1.ConsumerPacketData")
}

func init() { proto.RegisterFile("osmosis/types/v1beta1/wire.proto", fileDescriptor_c573c9158aa3b788) }

var fileDescriptor_c573c9158aa3b788 = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4f, 0x4f, 0xdb, 0x48,
	0x18, 0xc6, 0xed, 0xfc, 0xdb, 0x65, 0x60, 0x13, 0x33, 0x1b, 0x56, 0x56, 0x58, 0x59, 0x11, 0xbb,
	0x55, 0x11, 0x94, 0x58, 0xd0, 0xde, 0xab, 0x04, 0x9b, 0xc6, 0x55, 0xb0, 0xa3, 0x38, 0xa1, 0x6a,
	0x2f, 0xd6, 0xc4, 0x19, 0x92, 0x11, 0xb1, 0x27, 0xb2, 0x27, 0x50, 0xae, 0x3d, 0x55, 0x9c, 0xfa,
	0x05, 0x38, 0xf5, 0xd2, 0x7e, 0x13, 0x0e, 0x3d, 0x70, 0xec, 0xb1, 0x0d, 0xb7, 0x7e, 0x8a, 0xca,
	0x63, 0x37, 0xe6, 0xaf, 0xd4, 0x8b, 0xe5, 0xf9, 0xbd, 0xcf, 0xf3, 0xcc, 0xfb, 0x7a, 0xac, 0x01,
	0x55, 0x1a, 0x7a, 0x34, 0x24, 0xa1, 0xca, 0x4e, 0x27, 0x38, 0x54, 0x8f, 0xb7, 0xfb, 0x98, 0xa1,
	0x6d, 0xf5, 0x84, 0x04, 0xb8, 0x36, 0x09, 0x28, 0xa3, 0x70, 0x25, 0x51, 0xd4, 0xb8, 0xa2, 0x96,
	0x28, 0x2a, 0x8a, 0xcb, 0xb9, 0xda, 0x47, 0x21, 0x9e, 0xdb, 0x5c, 0x4a, 0xfc, 0xd8, 0x56, 0x29,
	0x0f, 0xe9, 0x90, 0xf2, 0x57, 0x35, 0x7a, 0x4b, 0xe8, 0x32, 0xf2, 0x88, 0x4f, 0x55, 0xfe, 0x4c,
	0xd0, 0xff, 0x49, 0x50, 0xc8, 0xd0, 0x11, 0xf1, 0x87, 0xf3, 0xac, 0x64, 0x9d, 0xa8, 0x56, 0x19,
	0xf6, 0x07, 0x38, 0xf0, 0x88, 0xcf, 0x54, 0xd4, 0x77, 0x49, 0xdc, 0x6f, 0x5c, 0x5c, 0xfb, 0x21,
	0x82, 0x05, 0x7b, 0x8c, 0xc2, 0x91, 0xe1, 0x1f, 0x52, 0xf8, 0x2f, 0x58, 0x38, 0x46, 0x63, 0x32,
	0x40, 0x8c, 0x06, 0xb2, 0x58, 0x15, 0xd7, 0x17, 0x3a, 0x29, 0x80, 0x9b, 0x60, 0x99, 0xf8, 0x87,
	0x01, 0x72, 0x19, 0xa1, 0xbe, 0x33, 0xc2, 0x64, 0x38, 0x62, 0x72, 0xa6, 0x2a, 0xae, 0x67, 0x3b,
	0x52, 0x5a, 0x68, 0x72, 0x0e, 0xcb, 0x20, 0x3f, 0xa1, 0x27, 0x38, 0x90, 0xb3, 0x5c, 0x10, 0x2f,
	0xe0, 0x13, 0x00, 0x19, 0x65, 0x68, 0xec, 0x84, 0xd1, 0x9e, 0x0e, 0xf2, 0xe8, 0xd4, 0x67, 0x72,
	0x8e, 0xef, 0x24, 0xf1, 0x0a, 0x6f, 0xa6, 0xce, 0x39, 0x7c, 0x04, 0x8a, 0xb1, 0xee, 0x57, 0xb6,
	0x9c, 0xe7, 0xca, 0xbf, 0x38, 0xdd, 0x4b, 0x20, 0x7c, 0x0c, 0x4a, 0x8c, 0x78, 0xd8, 0x49, 0x7b,
	0x90, 0x0b, 0x7c, 0xd3, 0x62, 0x84, 0x8d, 0x39, 0x5d, 0x6b, 0x80, 0x25, 0xdb, 0x1d, 0xe1, 0xc1,
	0x74, 0x8c, 0x7f, 0x63, 0xdc, 0x32, 0xc8, 0x23, 0x37, 0xaa, 0x64, 0x78, 0x25, 0x5e, 0xac, 0xbd,
	0xcb, 0x00, 0xb8, 0x4b, 0xfd, 0x70, 0xea, 0xe1, 0xa0, 0x8d, 0xdc, 0x23, 0xcc, 0x34, 0xc4, 0x10,
	0x7c, 0x0e, 0x72, 0xd1, 0x67, 0xe5, 0x29, 0xc5, 0x9d, 0xcd, 0xda, 0xbd, 0x27, 0x5f, 0x6b, 0x93,
	0x09, 0x1e, 0x1c, 0xa0, 0x71, 0x88, 0x99, 0x35, 0xc1, 0x01, 0x8a, 0xba, 0xea, 0x70, 0x23, 0x6c,
	0x81, 0x12, 0x9f, 0x2a, 0xcd, 0xe4, 0xfb, 0x2e, 0xee, 0x54, 0x1f, 0xc8, 0x9a, 0x9f, 0x5a, 0x53,
	0xe8, 0xdc, 0xb6, 0xc2, 0x1e, 0x80, 0x61, 0x32, 0xe9, 0xb5, 0xc0, 0x2c, 0x0f, 0xfc, 0xef, 0xa1,
	0xc0, 0x6b, 0x9f, 0xa6, 0x29, 0x74, 0xee, 0x09, 0x68, 0x14, 0x40, 0x6e, 0x80, 0x18, 0xda, 0xf8,
	0x22, 0x82, 0xf2, 0x7d, 0xb3, 0xc0, 0x12, 0x58, 0xec, 0x99, 0x76, 0x5b, 0xdf, 0x35, 0xf6, 0x0c,
	0x5d, 0x93, 0x04, 0x58, 0x06, 0xd2, 0x41, 0xbd, 0x65, 0x68, 0xf5, 0xae, 0xd5, 0x71, 0x1a, 0x96,
	0xa9, 0xe9, 0x9a, 0x24, 0xc2, 0x7f, 0x00, 0x4c, 0x69, 0xcf, 0x4c, 0x78, 0xe6, 0xa6, 0xfa, 0x65,
	0xdd, 0x68, 0xe9, 0x9a, 0x94, 0x85, 0x32, 0x28, 0xa7, 0xb4, 0x6b, 0xed, 0x37, 0xec, 0xae, 0x65,
	0xea, 0x9a, 0x94, 0xbb, 0x9d, 0x93, 0x38, 0xf2, 0x37, 0xf9, 0xbe, 0xa5, 0xc5, 0xdd, 0x14, 0xe0,
	0x0a, 0x58, 0x4e, 0xb9, 0xdd, 0xaa, 0xdb, 0x4d, 0x5d, 0x93, 0xfe, 0xd8, 0xf8, 0x2c, 0x82, 0x62,
	0xfa, 0x9b, 0x74, 0xa3, 0xe3, 0x78, 0x06, 0x56, 0x0d, 0x73, 0xaf, 0x53, 0xdf, 0xed, 0x1a, 0x96,
	0xe9, 0x74, 0x5f, 0xb7, 0x75, 0xe7, 0xc6, 0x60, 0x95, 0xbf, 0xcf, 0xce, 0xab, 0xa5, 0xd4, 0xa4,
	0x7b, 0x13, 0x76, 0x0a, 0xd5, 0xbb, 0x2e, 0xcd, 0xea, 0x35, 0x5a, 0xba, 0x63, 0x1b, 0x2f, 0x4c,
	0x49, 0xac, 0x14, 0xcf, 0xce, 0xab, 0x40, 0xa3, 0xd3, 0xfe, 0x18, 0xdb, 0x64, 0xe8, 0xc3, 0x0d,
	0x20, 0xdf, 0x35, 0xbc, 0x32, 0xbb, 0xc6, 0xbe, 0x2e, 0x65, 0x2a, 0x4b, 0x67, 0xe7, 0xd5, 0x3f,
	0x35, 0x7a, 0xe2, 0x47, 0xff, 0x71, 0x25, 0xf7, 0xfe, 0xa3, 0x22, 0x34, 0xec, 0x8b, 0xef, 0x8a,
	0xf0, 0x69, 0xa6, 0x08, 0x17, 0x33, 0x45, 0xbc, 0x9c, 0x29, 0xe2, 0xb7, 0x99, 0x22, 0x7e, 0xb8,
	0x52, 0x84, 0xcb, 0x2b, 0x45, 0xf8, 0x7a, 0xa5, 0x08, 0x6f, 0xb6, 0x87, 0x84, 0x8d, 0xa6, 0xfd,
	0x9a, 0x4b, 0x3d, 0x35, 0x39, 0xe9, 0xad, 0x31, 0xea, 0x87, 0xaa, 0x87, 0xc3, 0xd1, 0x56, 0x88,
	0xdd, 0x69, 0x40, 0xd8, 0xe9, 0x56, 0x38, 0x38, 0x52, 0xdf, 0xc6, 0x77, 0x41, 0xbf, 0xc0, 0x2f,
	0x83, 0xa7, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xe2, 0x97, 0xbe, 0xd3, 0x04, 0x00, 0x00,
}

func (m *SlashInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SlashInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SlashInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeInfraction != 0 {
		i = encodeVarintWire(dAtA, i, uint64(m.TimeInfraction))
		i--
		dAtA[i] = 0x30
	}
	if len(m.SlashFraction) > 0 {
		i -= len(m.SlashFraction)
		copy(dAtA[i:], m.SlashFraction)
		i = encodeVarintWire(dAtA, i, uint64(len(m.SlashFraction)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TotalSlashAmount) > 0 {
		i -= len(m.TotalSlashAmount)
		copy(dAtA[i:], m.TotalSlashAmount)
		i = encodeVarintWire(dAtA, i, uint64(len(m.TotalSlashAmount)))
		i--
		dAtA[i] = 0x22
	}
	if m.Power != 0 {
		i = encodeVarintWire(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x18
	}
	if m.InfractionHeight != 0 {
		i = encodeVarintWire(dAtA, i, uint64(m.InfractionHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintWire(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ScheduleInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduleInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduleInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Actor) > 0 {
		i -= len(m.Actor)
		copy(dAtA[i:], m.Actor)
		i = encodeVarintWire(dAtA, i, uint64(len(m.Actor)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintWire(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsumerPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size := m.Data.Size()
			i -= size
			if _, err := m.Data.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Type != 0 {
		i = encodeVarintWire(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConsumerPacketData_SlashPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerPacketData_SlashPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SlashPacketData != nil {
		{
			size, err := m.SlashPacketData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWire(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *ConsumerPacketData_SchedulePacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerPacketData_SchedulePacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SchedulePacketData != nil {
		{
			size, err := m.SchedulePacketData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWire(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func encodeVarintWire(dAtA []byte, offset int, v uint64) int {
	offset -= sovWire(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SlashInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovWire(uint64(l))
	}
	if m.InfractionHeight != 0 {
		n += 1 + sovWire(uint64(m.InfractionHeight))
	}
	if m.Power != 0 {
		n += 1 + sovWire(uint64(m.Power))
	}
	l = len(m.TotalSlashAmount)
	if l > 0 {
		n += 1 + l + sovWire(uint64(l))
	}
	l = len(m.SlashFraction)
	if l > 0 {
		n += 1 + l + sovWire(uint64(l))
	}
	if m.TimeInfraction != 0 {
		n += 1 + sovWire(uint64(m.TimeInfraction))
	}
	return n
}

func (m *ScheduleInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovWire(uint64(l))
	}
	l = len(m.Actor)
	if l > 0 {
		n += 1 + l + sovWire(uint64(l))
	}
	return n
}

func (m *ConsumerPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovWire(uint64(m.Type))
	}
	if m.Data != nil {
		n += m.Data.Size()
	}
	return n
}

func (m *ConsumerPacketData_SlashPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlashPacketData != nil {
		l = m.SlashPacketData.Size()
		n += 1 + l + sovWire(uint64(l))
	}
	return n
}
func (m *ConsumerPacketData_SchedulePacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SchedulePacketData != nil {
		l = m.SchedulePacketData.Size()
		n += 1 + l + sovWire(uint64(l))
	}
	return n
}

func sovWire(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWire(x uint64) (n int) {
	return sovWire(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SlashInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWire
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SlashInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SlashInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InfractionHeight", wireType)
			}
			m.InfractionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InfractionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSlashAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalSlashAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashFraction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeInfraction", wireType)
			}
			m.TimeInfraction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeInfraction |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWire(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWire
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduleInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWire
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduleInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduleInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWire(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWire
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsumerPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWire
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= PipedValsetOperation(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashPacketData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &SlashInfo{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Data = &ConsumerPacketData_SlashPacketData{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchedulePacketData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ScheduleInfo{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Data = &ConsumerPacketData_SchedulePacketData{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWire(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWire
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWire(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWire
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWire
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWire
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWire
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWire
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWire
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWire        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWire          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWire = fmt.Errorf("proto: unexpected end of group")
)
