// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/meshsecurityprovider/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/meshsecurity module.
type Params struct {
	// TimeoutPeriod has the unit time.Millisecond
	TimeoutPeriod        uint64 `protobuf:"varint,1,opt,name=timeout_period,json=timeoutPeriod,proto3" json:"timeout_period,omitempty"`
	VaultContractAddress string `protobuf:"bytes,2,opt,name=vault_contract_address,json=vaultContractAddress,proto3" json:"vault_contract_address,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51515613408cf3, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "osmosis.meshsecurityprovider.v1beta1.Params")
}

func init() {
	proto.RegisterFile("osmosis/meshsecurityprovider/v1beta1/params.proto", fileDescriptor_6d51515613408cf3)
}

var fileDescriptor_6d51515613408cf3 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0xfc, 0x30,
	0x18, 0xc6, 0x9b, 0x3f, 0x7f, 0x0e, 0x2c, 0x28, 0x78, 0x1c, 0x72, 0x9c, 0x10, 0x0f, 0x39, 0xe1,
	0x10, 0xda, 0x50, 0x74, 0x72, 0x53, 0xc1, 0xf9, 0xb8, 0xd1, 0xa5, 0xa4, 0x69, 0x68, 0x83, 0x97,
	0xbe, 0x25, 0x49, 0x8b, 0xf7, 0x15, 0x74, 0xf1, 0x23, 0x38, 0x3a, 0xfa, 0x31, 0x6e, 0xbc, 0xd1,
	0x51, 0xdb, 0x41, 0x3f, 0x86, 0x98, 0x46, 0xa7, 0x2e, 0xe1, 0xe5, 0x79, 0xf2, 0x3c, 0xc9, 0xfb,
	0xf3, 0x23, 0xd0, 0x12, 0xb4, 0xd0, 0x44, 0x72, 0x9d, 0x6b, 0xce, 0x2a, 0x25, 0xcc, 0xba, 0x54,
	0x50, 0x8b, 0x94, 0x2b, 0x52, 0x47, 0x09, 0x37, 0x34, 0x22, 0x25, 0x55, 0x54, 0xea, 0xb0, 0x54,
	0x60, 0x60, 0x38, 0x73, 0x91, 0xb0, 0x2f, 0x12, 0xba, 0xc8, 0x04, 0x33, 0x7b, 0x8d, 0x24, 0x54,
	0xf3, 0xbf, 0x1e, 0x06, 0xa2, 0xe8, 0x5a, 0x26, 0xa3, 0x0c, 0x32, 0xb0, 0x23, 0xf9, 0x99, 0x9c,
	0xba, 0x4f, 0xa5, 0x28, 0x80, 0xd8, 0xb3, 0x93, 0x8e, 0x1f, 0x91, 0x3f, 0x58, 0xd8, 0xf7, 0x87,
	0x27, 0xfe, 0x9e, 0x11, 0x92, 0x43, 0x65, 0xe2, 0x92, 0x2b, 0x01, 0xe9, 0x18, 0x4d, 0xd1, 0xfc,
	0xff, 0x72, 0xd7, 0xa9, 0x0b, 0x2b, 0x0e, 0xcf, 0xfd, 0x83, 0x9a, 0x56, 0x2b, 0x13, 0x33, 0x28,
	0x8c, 0xa2, 0xcc, 0xc4, 0x34, 0x4d, 0x15, 0xd7, 0x7a, 0xfc, 0x6f, 0x8a, 0xe6, 0x3b, 0xcb, 0x91,
	0x75, 0xaf, 0x9d, 0x79, 0xd9, 0x79, 0x17, 0xb3, 0xaf, 0xe7, 0x23, 0xf4, 0xf0, 0xf9, 0x7a, 0x7a,
	0xd8, 0x8b, 0xa2, 0xfb, 0xc2, 0x55, 0xbe, 0xf9, 0xc0, 0xde, 0x4b, 0x83, 0xbd, 0x4d, 0x83, 0xd1,
	0xb6, 0xc1, 0xe8, 0xbd, 0xc1, 0xe8, 0xa9, 0xc5, 0xde, 0xb6, 0xc5, 0xde, 0x5b, 0x8b, 0xbd, 0xdb,
	0x9b, 0x4c, 0x98, 0xbc, 0x4a, 0x42, 0x06, 0x92, 0x38, 0x52, 0xc1, 0x8a, 0x26, 0x1d, 0xe1, 0xe0,
	0xb7, 0x37, 0xd0, 0xe9, 0x1d, 0xb9, 0xef, 0xa7, 0x6e, 0xd6, 0x25, 0xd7, 0xc9, 0xc0, 0xae, 0x7f,
	0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x34, 0x89, 0x55, 0x25, 0xa2, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TimeoutPeriod != that1.TimeoutPeriod {
		return false
	}
	if this.VaultContractAddress != that1.VaultContractAddress {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VaultContractAddress) > 0 {
		i -= len(m.VaultContractAddress)
		copy(dAtA[i:], m.VaultContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.VaultContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.TimeoutPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TimeoutPeriod))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TimeoutPeriod != 0 {
		n += 1 + sovParams(uint64(m.TimeoutPeriod))
	}
	l = len(m.VaultContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutPeriod", wireType)
			}
			m.TimeoutPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VaultContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
