// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/meshsecurityprovider/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cometbft/cometbft/proto/tendermint/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/ibc-go/v9/modules/core/02-client/types"
	_07_tendermint "github.com/cosmos/ibc-go/v9/modules/light-clients/07-tendermint"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitConsumerMisbehaviour defines a message that reports a light client attack,
// also known as a misbehaviour, observed on a consumer chain
type MsgSubmitConsumerMisbehaviour struct {
	Submitter string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// The Misbehaviour of the consumer chain wrapping
	// two conflicting IBC headers
	Misbehaviour *_07_tendermint.Misbehaviour `protobuf:"bytes,2,opt,name=misbehaviour,proto3" json:"misbehaviour,omitempty"`
}

func (m *MsgSubmitConsumerMisbehaviour) Reset()         { *m = MsgSubmitConsumerMisbehaviour{} }
func (m *MsgSubmitConsumerMisbehaviour) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitConsumerMisbehaviour) ProtoMessage()    {}
func (*MsgSubmitConsumerMisbehaviour) Descriptor() ([]byte, []int) {
	return fileDescriptor_05534c9e44219747, []int{0}
}
func (m *MsgSubmitConsumerMisbehaviour) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitConsumerMisbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitConsumerMisbehaviour.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitConsumerMisbehaviour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitConsumerMisbehaviour.Merge(m, src)
}
func (m *MsgSubmitConsumerMisbehaviour) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitConsumerMisbehaviour) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitConsumerMisbehaviour.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitConsumerMisbehaviour proto.InternalMessageInfo

type MsgSubmitConsumerMisbehaviourResponse struct {
}

func (m *MsgSubmitConsumerMisbehaviourResponse) Reset()         { *m = MsgSubmitConsumerMisbehaviourResponse{} }
func (m *MsgSubmitConsumerMisbehaviourResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitConsumerMisbehaviourResponse) ProtoMessage()    {}
func (*MsgSubmitConsumerMisbehaviourResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05534c9e44219747, []int{1}
}
func (m *MsgSubmitConsumerMisbehaviourResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitConsumerMisbehaviourResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitConsumerMisbehaviourResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitConsumerMisbehaviourResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitConsumerMisbehaviourResponse.Merge(m, src)
}
func (m *MsgSubmitConsumerMisbehaviourResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitConsumerMisbehaviourResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitConsumerMisbehaviourResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitConsumerMisbehaviourResponse proto.InternalMessageInfo

// MsgSubmitConsumerDoubleVoting defines a message that reports
// a double signing infraction observed on a consumer chain
type MsgSubmitConsumerDoubleVoting struct {
	Submitter string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// The equivocation of the consumer chain wrapping
	// an evidence of a validator that signed two conflicting votes
	DuplicateVoteEvidence *types.DuplicateVoteEvidence `protobuf:"bytes,2,opt,name=duplicate_vote_evidence,json=duplicateVoteEvidence,proto3" json:"duplicate_vote_evidence,omitempty"`
	// The light client header of the infraction block
	InfractionBlockHeader *_07_tendermint.Header `protobuf:"bytes,3,opt,name=infraction_block_header,json=infractionBlockHeader,proto3" json:"infraction_block_header,omitempty"`
}

func (m *MsgSubmitConsumerDoubleVoting) Reset()         { *m = MsgSubmitConsumerDoubleVoting{} }
func (m *MsgSubmitConsumerDoubleVoting) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitConsumerDoubleVoting) ProtoMessage()    {}
func (*MsgSubmitConsumerDoubleVoting) Descriptor() ([]byte, []int) {
	return fileDescriptor_05534c9e44219747, []int{2}
}
func (m *MsgSubmitConsumerDoubleVoting) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitConsumerDoubleVoting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitConsumerDoubleVoting.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitConsumerDoubleVoting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitConsumerDoubleVoting.Merge(m, src)
}
func (m *MsgSubmitConsumerDoubleVoting) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitConsumerDoubleVoting) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitConsumerDoubleVoting.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitConsumerDoubleVoting proto.InternalMessageInfo

type MsgSubmitConsumerDoubleVotingResponse struct {
}

func (m *MsgSubmitConsumerDoubleVotingResponse) Reset()         { *m = MsgSubmitConsumerDoubleVotingResponse{} }
func (m *MsgSubmitConsumerDoubleVotingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitConsumerDoubleVotingResponse) ProtoMessage()    {}
func (*MsgSubmitConsumerDoubleVotingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05534c9e44219747, []int{3}
}
func (m *MsgSubmitConsumerDoubleVotingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitConsumerDoubleVotingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitConsumerDoubleVotingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitConsumerDoubleVotingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitConsumerDoubleVotingResponse.Merge(m, src)
}
func (m *MsgSubmitConsumerDoubleVotingResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitConsumerDoubleVotingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitConsumerDoubleVotingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitConsumerDoubleVotingResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitConsumerMisbehaviour)(nil), "osmosis.meshsecurityprovider.v1beta1.MsgSubmitConsumerMisbehaviour")
	proto.RegisterType((*MsgSubmitConsumerMisbehaviourResponse)(nil), "osmosis.meshsecurityprovider.v1beta1.MsgSubmitConsumerMisbehaviourResponse")
	proto.RegisterType((*MsgSubmitConsumerDoubleVoting)(nil), "osmosis.meshsecurityprovider.v1beta1.MsgSubmitConsumerDoubleVoting")
	proto.RegisterType((*MsgSubmitConsumerDoubleVotingResponse)(nil), "osmosis.meshsecurityprovider.v1beta1.MsgSubmitConsumerDoubleVotingResponse")
}

func init() {
	proto.RegisterFile("osmosis/meshsecurityprovider/v1beta1/tx.proto", fileDescriptor_05534c9e44219747)
}

var fileDescriptor_05534c9e44219747 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xb6, 0x5b, 0x09, 0xa9, 0x86, 0x85, 0x88, 0x92, 0x28, 0x02, 0xa7, 0x8a, 0x80, 0x56, 0x88,
	0xdc, 0x29, 0x65, 0x63, 0x6c, 0x0b, 0x42, 0x42, 0x91, 0x50, 0x90, 0x3a, 0x30, 0x10, 0xf9, 0xce,
	0x0f, 0xe7, 0x54, 0xfb, 0x5e, 0x74, 0x77, 0xb6, 0xda, 0x95, 0x89, 0x91, 0x89, 0xb9, 0x1b, 0x1b,
	0xe2, 0xcf, 0xe8, 0xd8, 0x91, 0x11, 0x92, 0xa1, 0xfc, 0x19, 0xc8, 0xf6, 0x99, 0xb8, 0x92, 0x95,
	0x42, 0xc5, 0x62, 0x3f, 0xbf, 0xf7, 0xf9, 0x7b, 0xdf, 0xfb, 0xee, 0x87, 0x37, 0x40, 0x9d, 0xa0,
	0x16, 0x9a, 0x26, 0xa0, 0xa7, 0x1a, 0x78, 0xaa, 0x84, 0x39, 0x99, 0x29, 0xcc, 0x44, 0x08, 0x8a,
	0x66, 0x43, 0x06, 0x26, 0x18, 0x52, 0x73, 0x4c, 0x66, 0x0a, 0x0d, 0xb6, 0x1e, 0x58, 0x38, 0x69,
	0x82, 0x13, 0x0b, 0xef, 0xfa, 0xbc, 0x80, 0x51, 0x16, 0x68, 0xf8, 0xc3, 0xc1, 0x51, 0xc8, 0x92,
	0xa5, 0xdb, 0xb6, 0xf5, 0x44, 0x47, 0x34, 0x1b, 0xe6, 0x2f, 0x5b, 0xb8, 0x13, 0x61, 0x84, 0x45,
	0x48, 0xf3, 0xc8, 0x66, 0x6f, 0x07, 0x89, 0x90, 0x48, 0x8b, 0xa7, 0x4d, 0xf5, 0x04, 0xe3, 0x94,
	0xa3, 0x02, 0xca, 0x63, 0x01, 0xd2, 0xe4, 0x34, 0x65, 0x64, 0x01, 0x34, 0x07, 0xc4, 0x22, 0x9a,
	0x9a, 0x32, 0xad, 0xa9, 0x01, 0x19, 0x82, 0x4a, 0x44, 0x09, 0x5e, 0x7e, 0x55, 0x8c, 0xb5, 0xba,
	0x39, 0x99, 0x81, 0xa6, 0x90, 0x0f, 0x25, 0x39, 0x94, 0x80, 0xfe, 0x17, 0xd7, 0xbb, 0x3f, 0xd2,
	0xd1, 0x9b, 0x94, 0x25, 0xc2, 0xec, 0xa3, 0xd4, 0x69, 0x02, 0x6a, 0x24, 0x34, 0x83, 0x69, 0x90,
	0x09, 0x4c, 0x55, 0xeb, 0x9e, 0xb7, 0xa1, 0x8b, 0xaa, 0x01, 0xd5, 0x71, 0xb7, 0xdc, 0x9d, 0x8d,
	0xf1, 0x32, 0xd1, 0x7a, 0xed, 0xdd, 0x4a, 0x6a, 0xe8, 0xce, 0xda, 0x96, 0xbb, 0x73, 0x73, 0xf7,
	0x09, 0x11, 0x8c, 0x93, 0xba, 0x50, 0x52, 0x93, 0x96, 0x0d, 0x49, 0xbd, 0xc3, 0xf8, 0x12, 0xc3,
	0xb3, 0xbb, 0x1f, 0x4f, 0x7b, 0xce, 0xaf, 0xd3, 0x9e, 0xf3, 0xe1, 0xe2, 0xdb, 0xe3, 0x65, 0xa7,
	0xfe, 0xb6, 0xf7, 0x70, 0xa5, 0xd0, 0x31, 0xe8, 0x19, 0x4a, 0x0d, 0xfd, 0xcf, 0x6b, 0x0d, 0x23,
	0x1d, 0x60, 0xca, 0x62, 0x38, 0x44, 0x23, 0x64, 0x74, 0xc5, 0x48, 0x13, 0xaf, 0x1d, 0xa6, 0xb3,
	0x58, 0xf0, 0xc0, 0xc0, 0x24, 0x43, 0x03, 0x93, 0xca, 0x33, 0x3b, 0xdd, 0x76, 0x7d, 0x98, 0xc2,
	0x55, 0x72, 0x50, 0xfd, 0x70, 0x88, 0x06, 0x9e, 0x5b, 0xf8, 0x78, 0x33, 0x6c, 0x4a, 0xb7, 0xde,
	0x79, 0x6d, 0x21, 0xdf, 0xab, 0x80, 0x1b, 0x81, 0x72, 0xc2, 0x62, 0xe4, 0x47, 0x93, 0x29, 0x04,
	0x21, 0xa8, 0xce, 0x7a, 0xd1, 0xe0, 0xd1, 0x55, 0xf6, 0xbd, 0x2c, 0xd0, 0xe3, 0xcd, 0x25, 0xcd,
	0x5e, 0xce, 0x52, 0xa6, 0xff, 0xc9, 0xc1, 0xba, 0x2f, 0x95, 0x83, 0xbb, 0x17, 0x6b, 0xde, 0xfa,
	0x48, 0x47, 0xad, 0xaf, 0xae, 0xd7, 0x5d, 0xb1, 0x33, 0xf6, 0xc9, 0xdf, 0x9c, 0x1b, 0xb2, 0x72,
	0xd5, 0xba, 0xaf, 0xfe, 0x03, 0x49, 0x25, 0xbc, 0x41, 0xf0, 0xa5, 0x75, 0xbf, 0xae, 0xe0, 0x3a,
	0xc9, 0xb5, 0x05, 0x37, 0x39, 0xbd, 0x17, 0x9e, 0xfd, 0xf4, 0x9d, 0xb3, 0xb9, 0xef, 0x9e, 0xcf,
	0x7d, 0xf7, 0xc7, 0xdc, 0x77, 0x3f, 0x2d, 0x7c, 0xe7, 0x7c, 0xe1, 0x3b, 0xdf, 0x17, 0xbe, 0xf3,
	0xf6, 0x45, 0x24, 0xcc, 0x34, 0x65, 0x84, 0x63, 0x42, 0x6d, 0xd3, 0x41, 0x1c, 0xb0, 0xf2, 0x5a,
	0x1b, 0x54, 0xad, 0x07, 0x3a, 0x3c, 0xa2, 0xc7, 0xcd, 0x57, 0x5d, 0xb1, 0x3b, 0xd9, 0x8d, 0xe2,
	0xac, 0x3f, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xf3, 0xa3, 0xda, 0x17, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// MsgSubmitConsumerMisbehaviour defines a message that reports a light client attack,
	// also known as a misbehaviour, observed on a consumer chain
	SubmitConsumerMisbehaviour(ctx context.Context, in *MsgSubmitConsumerMisbehaviour, opts ...grpc.CallOption) (*MsgSubmitConsumerMisbehaviourResponse, error)
	// MsgSubmitConsumerDoubleVoting defines a message that reports
	// a double signing infraction observed on a consumer chain
	SubmitConsumerDoubleVoting(ctx context.Context, in *MsgSubmitConsumerDoubleVoting, opts ...grpc.CallOption) (*MsgSubmitConsumerDoubleVotingResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitConsumerMisbehaviour(ctx context.Context, in *MsgSubmitConsumerMisbehaviour, opts ...grpc.CallOption) (*MsgSubmitConsumerMisbehaviourResponse, error) {
	out := new(MsgSubmitConsumerMisbehaviourResponse)
	err := c.cc.Invoke(ctx, "/osmosis.meshsecurityprovider.v1beta1.Msg/SubmitConsumerMisbehaviour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitConsumerDoubleVoting(ctx context.Context, in *MsgSubmitConsumerDoubleVoting, opts ...grpc.CallOption) (*MsgSubmitConsumerDoubleVotingResponse, error) {
	out := new(MsgSubmitConsumerDoubleVotingResponse)
	err := c.cc.Invoke(ctx, "/osmosis.meshsecurityprovider.v1beta1.Msg/SubmitConsumerDoubleVoting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// MsgSubmitConsumerMisbehaviour defines a message that reports a light client attack,
	// also known as a misbehaviour, observed on a consumer chain
	SubmitConsumerMisbehaviour(context.Context, *MsgSubmitConsumerMisbehaviour) (*MsgSubmitConsumerMisbehaviourResponse, error)
	// MsgSubmitConsumerDoubleVoting defines a message that reports
	// a double signing infraction observed on a consumer chain
	SubmitConsumerDoubleVoting(context.Context, *MsgSubmitConsumerDoubleVoting) (*MsgSubmitConsumerDoubleVotingResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitConsumerMisbehaviour(ctx context.Context, req *MsgSubmitConsumerMisbehaviour) (*MsgSubmitConsumerMisbehaviourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitConsumerMisbehaviour not implemented")
}
func (*UnimplementedMsgServer) SubmitConsumerDoubleVoting(ctx context.Context, req *MsgSubmitConsumerDoubleVoting) (*MsgSubmitConsumerDoubleVotingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitConsumerDoubleVoting not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitConsumerMisbehaviour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitConsumerMisbehaviour)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitConsumerMisbehaviour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.meshsecurityprovider.v1beta1.Msg/SubmitConsumerMisbehaviour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitConsumerMisbehaviour(ctx, req.(*MsgSubmitConsumerMisbehaviour))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitConsumerDoubleVoting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitConsumerDoubleVoting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitConsumerDoubleVoting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.meshsecurityprovider.v1beta1.Msg/SubmitConsumerDoubleVoting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitConsumerDoubleVoting(ctx, req.(*MsgSubmitConsumerDoubleVoting))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.meshsecurityprovider.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitConsumerMisbehaviour",
			Handler:    _Msg_SubmitConsumerMisbehaviour_Handler,
		},
		{
			MethodName: "SubmitConsumerDoubleVoting",
			Handler:    _Msg_SubmitConsumerDoubleVoting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/meshsecurityprovider/v1beta1/tx.proto",
}

func (m *MsgSubmitConsumerMisbehaviour) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitConsumerMisbehaviour) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitConsumerMisbehaviour) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Misbehaviour != nil {
		{
			size, err := m.Misbehaviour.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitConsumerMisbehaviourResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitConsumerMisbehaviourResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitConsumerMisbehaviourResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitConsumerDoubleVoting) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitConsumerDoubleVoting) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitConsumerDoubleVoting) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InfractionBlockHeader != nil {
		{
			size, err := m.InfractionBlockHeader.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DuplicateVoteEvidence != nil {
		{
			size, err := m.DuplicateVoteEvidence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitConsumerDoubleVotingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitConsumerDoubleVotingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitConsumerDoubleVotingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitConsumerMisbehaviour) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Misbehaviour != nil {
		l = m.Misbehaviour.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitConsumerMisbehaviourResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitConsumerDoubleVoting) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DuplicateVoteEvidence != nil {
		l = m.DuplicateVoteEvidence.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.InfractionBlockHeader != nil {
		l = m.InfractionBlockHeader.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitConsumerDoubleVotingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitConsumerMisbehaviour) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitConsumerMisbehaviour: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitConsumerMisbehaviour: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Misbehaviour", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Misbehaviour == nil {
				m.Misbehaviour = &_07_tendermint.Misbehaviour{}
			}
			if err := m.Misbehaviour.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitConsumerMisbehaviourResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitConsumerMisbehaviourResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitConsumerMisbehaviourResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitConsumerDoubleVoting) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitConsumerDoubleVoting: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitConsumerDoubleVoting: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DuplicateVoteEvidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DuplicateVoteEvidence == nil {
				m.DuplicateVoteEvidence = &types.DuplicateVoteEvidence{}
			}
			if err := m.DuplicateVoteEvidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InfractionBlockHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.InfractionBlockHeader == nil {
				m.InfractionBlockHeader = &_07_tendermint.Header{}
			}
			if err := m.InfractionBlockHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitConsumerDoubleVotingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitConsumerDoubleVotingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitConsumerDoubleVotingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
